# Generated by Django 3.2.9 on 2021-12-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0004_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
