# Generated by Django 3.2.9 on 2021-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0005_alter_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='profile.jpg', upload_to='Profile'),
        ),
    ]
