# Generated by Django 3.2.9 on 2021-12-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0006_alter_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fir_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('place', models.TextField(max_length=300)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epolice.user')),
            ],
        ),
    ]
