# Generated by Django 3.2.9 on 2021-12-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0007_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=300)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('crime', models.CharField(max_length=50)),
                ('crime_details', models.TextField(max_length=300)),
                ('pic', models.FileField(blank=True, null=True, upload_to='criminals')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epolice.user')),
            ],
        ),
    ]
