# Generated by Django 3.2.9 on 2021-12-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0009_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='Complain',
            new_name='complain',
        ),
    ]
