# Generated by Django 3.2.9 on 2022-01-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0010_rename_complain_complain_complain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain',
        ),
    ]
