# Generated by Django 3.2.9 on 2022-01-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0011_delete_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
