# Generated by Django 3.2.9 on 2022-01-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolice', '0012_fir_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='gender',
        ),
    ]
